[package]
name = "winit-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.78"
web-sys = "0.3.55"
winit = "0.25.0"

[workspace]
members = ["examples/*"]