[package]
name = "doomfire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
pixels = "0.7.0"
winit = "0.25.0"
winit_input_helper = "0.10.0"
winit-web = { path = "../.." }